CREATE DATABASE DEMO

USE DEMO

CREATE TABLE STUDENTS(
ROLLNO INT,
NAME VARCHAR(50)
)
--METHOD 1 WITH COLOUMN NAME 

INSERT INTO STUDENTS (ROLLNO,NAME) VALUES (1,'K');

INSERT INTO STUDENTS (NAME) VALUES ('KU');

--METHOD 2 WITHOUT COLUMN NAME

INSERT INTO STUDENTS VALUES (2,'KUN');

--INSERT INTO STUDENTS VALUES ('KUNJ',3) ->ERROR OF CONVERSION TYPE

--METHOD 3 INSERT WITH MULTIPLE VALUES

INSERT INTO STUDENTS VALUES (3,'KUNJ'),(4,'KAVAN');

--INSERT WITH NULL VALUES 

INSERT INTO STUDENTS (ROLLNO) VALUES (5);

INSERT INTO STUDENTS VALUES (6,'NULL');

--FETCH ALL DATA 

SELECT * FROM STUDENTS

--SELECT SPECIFIC COLUMN

SELECT NAME FROM STUDENTS;

--SELECT WITH CONDITIONS

SELECT ROLLNO FROM STUDENTS WHERE ROLLNO>2;

SELECT ROLLNO FROM STUDENTS WHERE ROLLNO%2=0;

SELECT ROLLNO FROM STUDENTS WHERE ROLLNO IS NULL;

SELECT NAME FROM STUDENTS WHERE NAME='NULL';

--LECTURE 3 18/06

--SELECT WITH NULL
SELECT * FROM STUDENTS WHERE NAME IS NULL; 

SELECT * FROM STUDENTS;

--TOP N RECORDS
SELECT TOP 2 NAME FROM STUDENTS;

--TOP PERCENT RECORD
SELECT TOP 10 PERCENT * FROM STUDENTS;

--SELECT UNIQUE RECORD 
SELECT DISTINCT NAME FROM STUDENTS;

--AND OPERATOR 
SELECT * FROM STUDENTS;